FROM gcr.io/kuar-demo/kuard-amd64:v0.9-green

# platform ARGs: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
ARG TARGETOS="linux"
ARG TARGETARCH="amd64"
ARG TARGETVARIANT=""
