apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: http-server
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: "100"
spec:
  selector:
    app.kubernetes.io/component: http-server
    {{- include "kuard.selectorLabels" $ | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
