#!/bin/bash
set -e
for lib in "$(dirname "$0")"/libs/*.bash; do source "${lib}"; done

function main {
  rm -f ./.github/workflows/*.gotmpl.yaml
  go run ./go/cmd/render-github-workflows
}

main "$@"
