name: external-helm-charts
on:
  push:
    branches:
      - main
    paths:
      - "third_party/helm/charts/**"
jobs:
  external-helm-charts:
    name: external-helm-charts
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gogcp-devcontainer:0.0.0
    permissions:
      contents: write
      id-token: write
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory /__w/gogcp/gogcp
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: helm auth (Google Artifact Registry)
        run: gcloud auth print-access-token | helm registry login --username="oauth2accesstoken" --password-stdin "europe-central2-docker.pkg.dev"
      - name: push
        run: ./scripts/external-helm-charts push
